// <auto-generated />
using System;
using Koa.Trixma.Back.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Koa.Trixma.Back.Data.Migrations
{
    [DbContext(typeof(TrixmaDbContext))]
    [Migration("20260505061506_AddFrequencyFieldsToUnit")]
    partial class AddFrequencyFieldsToUnit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Koa.Trixma.Back.Domain.Models.AlarmEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ActualValue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AlarmRuleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlarmRuleId");

                    b.ToTable("AlarmEvents");
                });

            modelBuilder.Entity("Koa.Trixma.Back.Domain.Models.AlarmRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MeasurementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("AlarmRules");
                });

            modelBuilder.Entity("Koa.Trixma.Back.Domain.Models.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id", "Timestamp");

                    b.HasIndex("UnitId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("Koa.Trixma.Back.Domain.Models.System", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("Koa.Trixma.Back.Domain.Models.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BatteryMv")
                        .HasColumnType("integer");

                    b.Property<int?>("GnssRequestIntervalS")
                        .HasColumnType("integer");

                    b.Property<string>("Imei")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastProvisionedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MacAddress")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PayloadIntervalS")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SystemId")
                        .HasColumnType("uuid");

                    b.Property<long?>("UptimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("nfcId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SystemId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Koa.Trixma.Back.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Koa.Trixma.Back.Domain.Models.AlarmEvent", b =>
                {
                    b.HasOne("Koa.Trixma.Back.Domain.Models.AlarmRule", "AlarmRule")
                        .WithMany("Events")
                        .HasForeignKey("AlarmRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmRule");
                });

            modelBuilder.Entity("Koa.Trixma.Back.Domain.Models.AlarmRule", b =>
                {
                    b.HasOne("Koa.Trixma.Back.Domain.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Koa.Trixma.Back.Domain.Models.Measurement", b =>
                {
                    b.HasOne("Koa.Trixma.Back.Domain.Models.Unit", "Unit")
                        .WithMany("Measurements")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Koa.Trixma.Back.Domain.Models.Unit", b =>
                {
                    b.HasOne("Koa.Trixma.Back.Domain.Models.System", null)
                        .WithMany("Units")
                        .HasForeignKey("SystemId");
                });

            modelBuilder.Entity("Koa.Trixma.Back.Domain.Models.AlarmRule", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Koa.Trixma.Back.Domain.Models.System", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("Koa.Trixma.Back.Domain.Models.Unit", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
