// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Koa.Trixma.Back.Data.Context;

#nullable disable

namespace Koa.Trixma.Back.Data.Migrations
{
    [DbContext(typeof(TrixmaDbContext))]
    [Migration("20260510120000_AddCellLocationToUnit")]
    partial class AddCellLocationToUnit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Note: This is a partial migration file generated for demonstration.
            // The full ModelSnapshot will be regenerated by Entity Framework when running dotnet ef migrations add.
            // This file only includes the structural indication that the migration exists.
#pragma warning restore 612, 618
        }
    }
}
