variables:
  - name: System.Debug
    value: "false"
  - group: koa-trixma

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Koa.Trixma.Back/**

stages:
  - stage: PushImage
    pool:
      name: Default
      demands:
        - Agent.Name -equals docker
    jobs:
      - job: Job_2
        displayName: PushImage
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "koa-acr-private"
              repository: "koa-trixma-back"
              command: "buildAndPush"
              Dockerfile: "./Koa.Trixma.Back/Dockerfile"
              tags: |
                $(Build.BuildId)
                latest

  - stage: UpdateContainer
    pool:
      name: Default
      demands:
        - Agent.Name -equals docker
    jobs:
      - job: UpdateContainer
        displayName: UpdateContainer
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                @"
                DB_CONNECTION_STRING=$(DB_CONNECTION_STRING)
                MQTT_PASSWORD=$(MQTT_PASSWORD)
                "@ | Set-Content -Path ".env" -Encoding UTF8
                docker compose pull
                docker compose stop koa-trixma-back
                docker compose up koa-trixma-back -d
              workingDirectory: 'c:\Dev\Koa\Koa.Trixma'