version: "3.9"
name: Koa-Trixma-Back-System
services:
  koa-trixma-back:
    image: koaacr.azurecr.io/koa-trixma-back:latest
    restart: always
    environment:
      ConnectionStrings__Database: "${DB_CONNECTION_STRING}"
      Mqtt__Password: "${MQTT_PASSWORD}"
    ports:
      - "5101:443"
    networks:
      - koa-trixma-back-net

networks:
  koa-trixma-back-net:
    name: koa-trixma-back-net
    attachable: true
